name: quizz_app
description: Get ready to know more about Morocco.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  firebase_storage: ^10.2.18
  cloud_firestore: ^3.1.18
  google_sign_in: 5.3.3
  github_sign_in: ^0.0.5-dev.4
  google_fonts: 3.0.1
  provider: ^6.0.3
  font_awesome_flutter: ^10.1.0
  flutter_spinkit: ^5.1.0
  json_annotation: 4.5.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  confetti: ^0.7.0
  audioplayers: ^1.0.1
  uuid: ^3.0.6

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logo.png'

dev_dependencies:
  flutter_launcher_icons: '^0.9.2'
  flutter_test:
    sdk: flutter

  build_runner: ^2.0.0
  json_serializable: ^6.0.0

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/covers/
    - assets/sounds/
