// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ-bkDgApQRH5VdiAaCONgFOmbeyUvG5E',
    appId: '1:644679977581:web:378c557be0b5b9363acd64',
    messagingSenderId: '644679977581',
    projectId: 'quiz-app-be632',
    authDomain: 'quiz-app-be632.firebaseapp.com',
    storageBucket: 'quiz-app-be632.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbcgoBFHyDu1Mxfrj5ENggc6w4GlYG4RI',
    appId: '1:644679977581:android:749a0e03e8a3b0463acd64',
    messagingSenderId: '644679977581',
    projectId: 'quiz-app-be632',
    storageBucket: 'quiz-app-be632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cNYx1qom1X9MTg6JsbQ0Tkmf7P9c2eY',
    appId: '1:644679977581:ios:b5c2d3a73ef4cd343acd64',
    messagingSenderId: '644679977581',
    projectId: 'quiz-app-be632',
    storageBucket: 'quiz-app-be632.appspot.com',
    iosClientId: '644679977581-rshvd2b3a64hkl0fqhgicjnqm7u3mt7f.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzApp',
  );
}
